version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: docker/prod/app/Dockerfile
    command: bundle exec puma -C config/puma.rb
    volumes:
      - /var/www/samtra
    expose:
      - "3000"
  web:
    build:
      context: .
      dockerfile: docker/prod/web/Dockerfile
    links:
      - app
    ports:
      - "80:80"