version: '3.2'
services:
  devapp:
    build: 
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "3000:3000"
    entrypoint: ./docker-entrypoint.dev.sh
    command: "bundle exec rails server -b 0.0.0.0"

# building image & running -> docker-compose -f docker-compose.dev.yml up
# on bash -> docker run -it -p 3000:3000 -v $(pwd):/app samtra_devapp
# on fish -> docker run -it -p 3000:3000 -v (pwd):/app --name samtra_devapp samtra_devapp

# open bash on the image -> docker run -it samtra_devapp /bin/bash

# Remove all the images -> docker image prune -a

# Stop all the running containers -> docker stop (docker ps -a -q)

# bundle exec rake db:seed는 개발 환결에서 따로 만들어놔야함
