version: '3'
services:
  devapp:
    build: 
      context: .
      dockerfile: docker/dev/Dockerfile
    command: "bundle exec rails server -b 0.0.0.0"
    volumes:
      - /app
    expose:
      - "3000"


# on bash -> docker run -it -p 3000:3000 -v $(pwd):/app samtra_devapp
# on fish -> docker run -it -p 3000:3000 -v (pwd):/app samtra_devapp