version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: docker/prod/app/Dockerfile
    # entrypoint: ./docker-entrypoint.dev.sh    
    # command: "bundle exec puma -C config/puma.rb"
    # volumes:
    #   - /var/www/samtra
    ports:
      - "80:80"